;;;; package.lisp

(defpackage "GEMINI"
  (:shadowing-import-from "FUNCTION" "COMPOSE")
  (:shadowing-import-from "NAMED-LET" "LET" "NAMED-LAMBDA")
  (:shadowing-import-from "SERIES" "DEFUN" "FUNCALL" "LET*" "MULTIPLE-VALUE-BIND")
  (:use "ALEXANDRIA" "CL" "FOLD" "FUNCTION" "NAMED-LET" "SERIES")
  (:export
   "*CACHED-CONTENT*"
   "*CANDIDATE-COUNT*"
   "*ENABLE-ADVANCED-CIVIC-ANSWERS*"
   "*FREQUENCY-PENALTY*"
   "*GEMINI-OUTPUT-PROCESSOR*"
   "*GENERATION-CONFIG*"
   "*GOOGLE-API-KEY*"
   "*INCLUDE-THOUGHTS*"
   "*LANGUAGE-CODE*"
   "*LOGPROBS*"
   "*MAX-OUTPUT-TOKENS*"
   "*MEDIA-RESOLUTION*"
   "*MULTI-SPEAKER-VOICE-CONFIG*"
   "*PREBUILT-VOICE-CONFIG*"
   "*PRESENCE-PENALTY*"
   "*RESPONSE-JSON-SCHEMA*"
   "*RESPONSE-LOGPROBS*"
   "*RESPONSE-MIME-TYPE*"
   "*RESPONSE-MODALITIES*"
   "*RESPONSE-SCHEMA*"
   "*SAFETY-SETTINGS*"
   "*SEED*"
   "*SPEECH-CONFIG*"
   "*STOP-SEQUENCES*"
   "*SYSTEM-INSTRUCTION*"
   "*TEMPERATURE*"
   "*THINKING-BUDGET*"
   "*THINKING-CONFIG*"
   "*TOOL-CONFIG*"
   "*TOOLS*"
   "*TOP-K*"
   "*TOP-P*"
   "*VOICE-CONFIG*"
   "*VOICE-NAME*"
   "INVOKE-GEMINI"
   ))
